server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:https://github.com/SharvilGit15/ecommerce-config/tree/main
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
